# Generated by Django 4.0.3 on 2022-08-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iOrder', '0006_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
