# Generated by Django 4.0.3 on 2022-08-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iOrder', '0008_alter_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
    ]
